const sites = [
  "https://abdomenplasticsurgery.intpatient.com/",
  "https://abdominoplasty.intpatient.com/",
  "https://allelective.intpatient.com/",
  "https://angiography.intpatient.com/",
  "https://angioplasty.intpatient.com/",
  "https://anteriorligament.intpatient.com/",
  "https://antiageing.intpatient.com/",
  "https://antiagingstemcell.intpatient.com/",
  "https://antiagingweightloss.intpatient.com/",
  "https://aorticrepair.intpatient.com/",
  "https://aplasticanaemia.intpatient.com/",
  "https://ar-apollohospitals.intpatient.com",
  "https://ar-apollohyderabad.intpatient.com/",
  "https://ar-blkhospital.intpatient.com/",
  "https://ar-bonemarrowtransplant.intpatient.com/",
  "https://ar-breastcancer.intpatient.com/",
  "https://ar-cabginindia.intpatient.com/",
  "https://ar-cancerindia.intpatient.com/",
  "https://ar-cardiachospitals.intpatient.com/",
  "https://ar-cervicalcancer.intpatient.com/",
  "https://ar-cosmetichospitals.intpatient.com/",
  "https://ar-deepstimulation.intpatient.com/",
  "https://ar-dentalhospitals.intpatient.com/",
  "https://ar-eyehospitals.intpatient.com/",
  "https://ar-gicancer.intpatient.com/",
  "https://ar-globalhospital.intpatient.com/",
  "https://ar-hairtransplant.intpatient.com/",
  "https://ar-hcghospital.intpatient.com/",
  "https://ar-hearttransplant.intpatient.com/",
  "https://ar-hipreplacement.intpatient.com/",
  "https://ar-holeinheart.intpatient.com/",
  "https://ar-hospitalsindia.intpatient.com/",
  "https://ar-ivfhospitals.intpatient.com/",
  "https://ar-jaslokhospital.intpatient.com/",
  "https://ar-kidneytransplant.intpatient.com/",
  "https://ar-kneereplacement.intpatient.com/",
  "https://ar-livertransplant.intpatient.com/",
  "https://ar-lungtransplant.intpatient.com/",
  "https://ar-lungtransplant.intpatient.com/",
  "https://ar-maxhospital.intpatient.com/",
  "https://ar-neurologyhospitals.intpatient.com/",
  "https://ar-oncologyhospitals.intpatient.com/",
  "https://ar-orthopedichospital.intpatient.com/",
  "https://ar-pacemaker.intpatient.com/",
  "https://ar-prostatecancer.intpatient.com/",
  "https://ar-shoulderreplacement.intpatient.com/",
  "https://ar-stemcell.intpatient.com/",
  "https://ar-strokehospital.intpatient.com/",
  "https://ar-surgeryinindia.intpatient.com/",
  "https://ar-transplanthospitals.intpatient.com/",
  "https://artemishospital.intpatient.com/",
  "https://arthroscopicsurgery.intpatient.com/",
  "https://artificialdiscreplacement.intpatient.com/",
  "https://asianhearthospital.intpatient.com/",
  "https://astigmatismtreatment.intpatient.com/",
  "https://atrialfibrillation.intpatient.com/",
  "https://atrialseptaldefect.intpatient.com/",
  "https://atrioventriculardefect.intpatient.com/",
  "https://ayurveda.intpatient.com/",
  "https://balloonatrialseptostomy.intpatient.com/",
  "https://basalcellcancer.intpatient.com/",
  "https://biventricular.intpatient.com/",
  "https://bladdercancertreatment.intpatient.com/",
  "https://bladderincision.intpatient.com/",
  "https://bloodcancer.intpatient.com/",
  "https://bonemarrowtransplant.intpatient.com/",
  "https://brachialplexusinjury.intpatient.com/",
  "https://braintumor.intpatient.com/",
  "https://breastaugmentation.intpatient.com/",
  "https://breastcancer.intpatient.com/",
  "https://browliftsurgery.intpatient.com/",
  "https://browplastyforeheadlift.intpatient.com/",
  "https://bunionectomy.intpatient.com/",
  "https://cabginindia.intpatient.com/",
  "https://cancerindia.intpatient.com/",
  "https://carcinoidtumourstreatment.intpatient.com/",
  "https://cardiachospitals.intpatient.com/",
  "https://cardiologyfortis.intpatient.com/",
  "https://carehospital.intpatient.com/",
  "https://carotidarterystenosis.intpatient.com/",
  "https://carpaltunnel.intpatient.com/",
  "https://cerebralangiogram.intpatient.com/",
  "https://cerebralangioplasty.intpatient.com",
  "https://cervicalcancer.intpatient.com/",
  "https://cervicalfusion.intpatient.com/",
  "https://cheekaugmentation.intpatient.com/",
  "https://medanta.intpatient.com/",
  "https://apollodelhi.intpatient.com/",
  "https://cancerapollo.intpatient.com/",
  "https://fortisescortsdelhi.intpatient.com/",
  "https://new-landing-pages.vercel.app/",
  "https://hosplan.com/hospital/fortis-hospital-shalimar-bagh",
  "https://chemotherapy.intpatient.com		",
  "https://chinimplantsurgery.intpatient.com		",
  "https://cholecystectomy.intpatient.com		",
  "https://cholesteatomatreatment.intpatient.com		",
  "https://chronichaematoma.intpatient.com		",
  "https://chroniclymphocyticleukaemia.intpatient.com		",
  "https://chronicmyelomonocytic.intpatient.com	",
  "https://cleftlipsurgery.intpatient.com	",
  "https://cleftpalatesurgery.intpatient.com	",
  "https://cloacalmalformationsurgery.intpatient.com	",
  "https://cochlearimplant.intpatient.com	",
  "https://coloncancer.intpatient.com	",
  "https://comprehensivemyelopathy.intpatient.com	",
  "https://congenitalheartdisorder.intpatient.com	",
  "https://congenitallimbdefects.intpatient.com	",
  "https://coronaryangioplasty.intpatient.com	",
  "https://cosmetichospitals.intpatient.com	",
  "https://cosmeticrhinoplasty.intpatient.com	",
  "https://craniofacialreconstruction.intpatient.com	",
  "https://craniotomysurgery.intpatient.com	",
  "https://csfshunt.intpatient.com	",
  "https://cyberknifetreatment.intpatient.com	",
  "https://dedicatedmanager.intpatient.com	",
  "https://deepstimulation.intpatient.com	",
  "https://demo.intpatient.com	",
  "https://dentalhospitals.intpatient.com	",
  "https://deviceclosureasd.intpatient.com	",
  "https://devtest.intpatient.com	",
  "https://diabetestreatment.intpatient.com	",
  "https://dvrtwovalves.intpatient.com	",
  "https://easyfollowups.intpatient.com	",
  "https://electrophysiology.intpatient.com	",
  "https://endometrialresection.intpatient.com	",
  "https://endopyelotomy.intpatient.com	",
  "https://eyehospitals.intpatient.com	",
  "https://faceliftsurgery.intpatient.com		",
  "https://fortisarab.intpatient.com",
  "https://fortisbangalore.intpatient.com",
  "https://fortisescortsdelhi.intpatient.com",
  "https://fortisgurgaon.intpatient.com",
  "https://fortishospital.intpatient.com",
  "https://fortismalarchennai.intpatient.com",
  "https://fortismumbai.intpatient.com",
  "https://gallbladdercancer.intpatient.com		",
  "https://gallbladdersurgery.intpatient.com		",
  "https://gastricbandingsurgery.intpatient.com		",
  "https://gastricbypasssurgery.intpatient.com		",
  "https://gastricsleevesurgery.intpatient.com",
  "https://gicancer.intpatient.com",
  "https://globalhospital.intpatient.com",
  "https://gynaecology.intpatient.com",
  "https://hairtransplant.intpatient.com",
  "https://handy-amplifier-259811.appspot.com	",
  "https://hcghospital.intpatient.com",
  "https://hearttransplant.intpatient.com",
  "https://heartvalvereplacement.intpatient.com",
  "https://hepatitistreatment.intpatient.com",
  "https://herniarepair.intpatient.com",
  "https://hipreplacement.intpatient.com		",
  "https://hiranandanihospital.intpatient.com",
  "https://holeaspiration.intpatient.com",
  "https://holeinheart.intpatient.com",
  "https://hospitalsbangalore.intpatient.com",
  "https://hospitalschennai.intpatient.com",
  "https://hospitalsdelhi.intpatient.com",
  "https://hospitalshyderabad.intpatient.com",
  "https://hospitalsindia.intpatient.com",
  "https://hospitalsmumbai.intpatient.com",
  "https://hospitaltest.intpatient.com	",
  "https://hsctforms.intpatient.com",
  "https://hysterectomy.intpatient.com",
  "https://hysteroscopicmyomectomy.intpatient.com",
  "https://hysteroscopicpolypectomy.intpatient.com",
  "https://imageguidedradiation.intpatient.com",
  "https://incompatiblekidney.intpatient.com",
  "https://intensitymodulated.intpatient.com",
  "https://intraocularcataractlens.intpatient.com",
  "https://ivfhospitals.intpatient.com",
  "https://jaslokhospital.intpatient.com",
  "https://jointreplacement.intpatient.com",
  "https://kidneyapollo.intpatient.com		",
  "https://kidneytransplant.intpatient.com",
  "https://kneereplacement.intpatient.com",
  "https://kokilabenhospital.intpatient.com",
  "https://laparoscopiccholesytectomy.intpatient.com",
  "https://lapfundoplication.intpatient.com",
  "https://laproscopicdiscectomy.intpatient.com",
  "https://lasiksurgery.intpatient.com",
  "https://leukemia.intpatient.com",
  "https://lilavatihospital.intpatient.com",
  "https://lipsaugmentation.intpatient.com",
  "https://liverapollo.intpatient.com	",
  "https://livercancer.intpatient.com",
  "https://liverfortis.intpatient.com		",
  "https://liverglobal.intpatient.com",
  "https://liverpakistan.intpatient.com",
  "https://livertransplant.intpatient.com",
  "https://lumbarfusion.intpatient.com",
  "https://lungapollo.intpatient.com		",
  "https://lungcancer.intpatient.com",
  "https://lungtransplant.intpatient.com	 ",
  "https://lvad.intpatient.com	  ",
  "https://lymphoma.intpatient.com	  ",
  "https://maxhospital.intpatient.com	 ",
  "https://maxhospitalindia.intpatient.com	 ",
  "https://maxsaket.intpatient.com	",
  "https://medanta.intpatient.com	",
  "https://medantahospital.intpatient.com	 ",
  "https://mh.intpatient.com	  	",
  "https://multiplemyeloma.intpatient.com	 ",
  "https://multiplescelorosis.intpatient.com	  ",
  "https://multiplesclerosis.intpatient.com	 ",
  "https://myomectomy.intpatient.com	 ",
  "https://narayanahospital.intpatient.com	",
  "https://neurologyhospitals.intpatient.com	 ",
  "https://neurologyindia.intpatient.com	 ",
  "https://novaivi.intpatient.com	",
  "https://nr-oncologyhospitals.intpatient.com	",
  "https://oncologyhospitals.intpatient.com",
  "https://opticalinternal.intpatient.com	",
  "https://oralcancer.intpatient.com	 ",
  "https://orthopedichospital.intpatient.com	 ",
  "https://ovariancystectomy.intpatient.com	",
  "https://pacemaker.intpatient.com	 ",
  "https://partialpenectomy.intpatient.com	 ",
  "https://peripheralsurgery.intpatient.com	 ",
  "https://prostatecancer.intpatient.com	 ",
  "https://prostatectomy.intpatient.com	 ",
  "https://radiationtherapy.intpatient.com	 ",
  "https://radicalprostatectomy.intpatient.com	 ",
  "https://radiofrequencyrhizotomy.intpatient.com	",
  "https://rapidarc.intpatient.com	 ",
  "https://relainstitute.intpatient.com	",
  "https://ru-apollohospitals.intpatient.com	 ",
  "https://ru-ayurveda.intpatient.com",
  "https://ru-braintumor.intpatient.com	 ",
  "https://ru-breastcancer.intpatient.com	",
  "https://ru-cancerindia.intpatient.com	",
  "https://ru-cardiachospitals.intpatient.com	",
  "https://ru-fortishospital.intpatient.com	",
  "https://ru-gallbladdercancer.intpatient.com	",
  "https://ru-hospitalsindia.intpatient.com	",
  "https://ru-medantahospital.intpatient.com	",
  "https://ru-prostatecancer.intpatient.com	",
  "https://ru-spinalompression.intpatient.com	 ",
  "https://ru-spinalfusion.intpatient.com",
  "https://ru-surgeryinindia.intpatient.com	",
  "https://ru-treatmentinindia.intpatient.com	",
  "https://sakrahospital.intpatient.com	 ",
  "https://savecost.intpatient.com	",
  "https://sevenhillshospital.intpatient.com	",
  "https://shalbyhospital.intpatient.com	 ",
  "https://shavingofcartilage.intpatient.com	",
  "https://shoulderreplacement.intpatient.com	",
  "https://sicklecell.intpatient.com	 ",
  "https://simschennai.intpatient.com",
  "https://simshospital.intpatient.com	",
  "https://spinalompression.intpatient.com	",
  "https://spinalfusion.intpatient.com	  ",
  "https://staging.handy-amplifier-259811.appspot.com	 ",
  "https://stemcell.intpatient.com	  ",
  "https://stomachcancer.intpatient.com	",
  "https://stroke.intpatient.com	 ",
  "https://surgeryinindia.intpatient.com	 ",
  "https://surgicalatrial.intpatient.com	 ",
  "https://systemicpulmonary.intpatient.com	",
  "https://thalassemia.intpatient.com	 ",
  "https://thymectomy.intpatient.com	 ",
  "https://topratedhospitals.intpatient.com	",
  "https://totalpenectomy.intpatient.com	 ",
  "https://transplanthospitals.intpatient.com	  ",
  "https://treatmentinindia.intpatient.com	",
  "https://turbendoscopic.intpatient.com	 ",
  "https://turptuevplaser.intpatient.com	  ",
  "https://vagalnervestimulator.intpatient.com	   ",
  "https://valvereplacement.intpatient.com	   ",
  "https://vasectomy.intpatient.com	  	   	 	",
  "https://ventricularseptal.intpatient.com	   ",
  "https://wockhardthospitals.intpatient.com	 ",
  "https://www.intpatient.com 	 	",
  "https://yashodahospital.intpatient.com	",
];
const len = sites.length;
document.getElementById(
  "site-length"
).innerHTML = `<p>    ${len} landing pages</p>`;
//make thi asynchronous function

const checkStatusCode = () => {
  const writehere = document.getElementById("site-status");
  sites.forEach((site) => {
    axios
      .get(site)
      .then((response) => {
        if (response.status === 200) {
          writehere.innerHTML += `<a class="up" href=${site} style='color:white;'>${site}  is up</a>`;
        } else {
          writehere.innerHTML += `<a class="down" href=${site} style='color:white;'>${site}  is down</a>`;
        }
      })
      .catch((err) => {
        writehere.innerHTML += `<div class="down">
        <a  href=${site} style='color:white;'>${site}  is down</a>
        <details>
  <summary>more details</summary>
  <p> status Code :  ${err.response.status} </p>
  <p>  ${err.message} </p>
</details`;
      });
  });
};
const sortbyUp = () => {};
const sortbyDown = () => {};
checkStatusCode();
